---
- hosts: all
# Try Somthing like this
# vars:
#  - app_path: /home/vagrant/myapp/app.js
#  - node_path: /usr/bin/node
  tasks:
  -
    name: install myservice systemd unit file
    template: src=templete.j2 dest=/etc/systemd/system/myapp.service
    become: yes

  -
    name: start myservice
    systemd: state=started name=myapp daemon_reload=yes  
    become: yes   
